version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    environment:
      - "JEKYLL_GITHUB_TOKEN:11ac5264ec0d6ceb348e2dca429f43ef7416d614"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true
